# Generated by Django 5.0.8 on 2026-03-16 01:57

import django.utils.timezone
import leases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to=leases.models.contract_upload_path, verbose_name='Contrato Escaneado'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('ended', 'Finalizado'), ('maintenance', 'Mantenimiento')], default='active', max_length=20),
        ),
    ]
