# Generated by Django 5.0.8 on 2026-02-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('users', '0002_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.client'),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='attemted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
