# Generated by Django 5.0.8 on 2026-02-24 21:13

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('HELD', 'Custodia'), ('PARTIALY', 'Devuelto Parcialmente'), ('RETURNED', 'Devuelto')], default='HELD', max_length=20)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deposits', to=settings.AUTH_USER_MODEL)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='leases.lease')),
            ],
        ),
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text=' Usa el dia 1 del mes ej: 2026-02-01')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado'), ('late', 'Atrasado')], default='pending', max_length=10)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='leases.lease')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=billing.models.receipt_upload_path)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.rentinvoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_ren_status_e3064f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['period'], name='billing_ren_period_d442f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentinvoice',
            constraint=models.UniqueConstraint(fields=('lease', 'period'), name='unique_invoice_per_lease_and_period'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_on'], name='billing_pay_paid_on_a0fdca_idx'),
        ),
    ]
