# Generated by Django 5.0.8 on 2026-03-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('HELD', 'Custodia'), ('PARTIALLY_RETURNED', 'Devuelto Parcialmente'), ('RETURNED', 'Devuelto')], default='HELD', max_length=20),
        ),
    ]
